modLoader = "${modLoader}"
loaderVersion = "${loaderVersion}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "logo.png"
authors = "Team Harmony"
credits = "jackulee, vveniamin, cuttleboneten"
description = '''
    A mod that changes the way how cakes are cooking
'''

[[dependencies.cakeworks]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cakeworks]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cakeworks]]
modId = "blueprint"
mandatory = true
type = "required"
versionRange = "[${blueprint_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cakeworks]]
modId = "neapolitan"
mandatory = false
type = "optional"
versionRange = "[${neapolitan_version},)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mixins.cakeworks.json"